#server:
#  port: ${SERVER_PORT:8085}

#spring:
#  kafka:
#    producer:
#      bootstrap-servers: localhost:9092
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.apache.kafka.common.serialization.StringSerializer

topic:
  equipment: topic_equipment_kafka